spring:
  main:
    web-application-type: none
  profiles:
    active: test

server:
  port: 0
  compression:
    enabled: true

sookiwi:
  name: Soo
  age: ${random.int(1,100)}
  full-name: ${sookiwi.name} Kim
  session-timeout: 25s
