spring:
  main:
    web-application-type: none
  profiles:
    active: test
  output:
    ansi:
      enabled: always

server:
  port: 0
  compression:
    enabled: true

#logging:
#  file: filename
#  path: logs # directory
#  level:
#    com.example.demo: debug

sookiwi:
  name: Soo
  age: ${random.int(1,100)}
  full-name: ${sookiwi.name} Kim
  session-timeout: 25s
